export const COMMON_MEAL_SEED = [
  {
    id: "seed_chicken_rice_bowl",
    name: "Chicken Rice Bowl",
    calories: 520,
    protein: 40,
    carbs: 58,
    fat: 14,
    detail: "Grilled chicken • jasmine rice • mixed veggies",
  },
  {
    id: "seed_turkey_sandwich",
    name: "Turkey Sandwich",
    calories: 430,
    protein: 30,
    carbs: 46,
    fat: 12,
    detail: "Turkey breast • whole wheat bread • light mayo",
  },
  {
    id: "seed_greek_yogurt_parfait",
    name: "Greek Yogurt Parfait",
    calories: 280,
    protein: 20,
    carbs: 30,
    fat: 8,
    detail: "Greek yogurt • berries • granola",
  },
  {
    id: "seed_salmon_salad",
    name: "Salmon Salad",
    calories: 460,
    protein: 36,
    carbs: 18,
    fat: 24,
    detail: "Salmon • greens • olive oil vinaigrette",
  },
  {
    id: "seed_oatmeal_with_banana",
    name: "Oatmeal With Banana",
    calories: 350,
    protein: 12,
    carbs: 58,
    fat: 7,
    detail: "Rolled oats • banana • peanut butter",
  },
  {
    id: "seed_egg_white_scramble",
    name: "Egg White Scramble",
    calories: 300,
    protein: 28,
    carbs: 16,
    fat: 12,
    detail: "Egg whites • spinach • feta",
  },
  {
    id: "seed_beef_burrito_bowl",
    name: "Beef Burrito Bowl",
    calories: 610,
    protein: 42,
    carbs: 62,
    fat: 20,
    detail: "Lean beef • rice • beans • salsa",
  },
  {
    id: "seed_protein_smoothie",
    name: "Protein Smoothie",
    calories: 320,
    protein: 32,
    carbs: 28,
    fat: 8,
    detail: "Whey protein • milk • banana",
  },
  {
    id: "seed_tuna_wrap",
    name: "Tuna Wrap",
    calories: 390,
    protein: 33,
    carbs: 34,
    fat: 12,
    detail: "Tuna • whole wheat wrap • lettuce",
  },
  {
    id: "seed_avocado_toast_and_eggs",
    name: "Avocado Toast And Eggs",
    calories: 410,
    protein: 19,
    carbs: 34,
    fat: 22,
    detail: "Sourdough • avocado • 2 eggs",
  },
  {
    id: "seed_shrimp_stir_fry",
    name: "Shrimp Stir Fry",
    calories: 470,
    protein: 39,
    carbs: 44,
    fat: 14,
    detail: "Shrimp • veggies • rice",
  },
  {
    id: "seed_grilled_chicken_caesar",
    name: "Grilled Chicken Caesar",
    calories: 440,
    protein: 41,
    carbs: 16,
    fat: 24,
    detail: "Chicken • romaine • parmesan",
  },
  {
    id: "seed_tofu_veggie_bowl",
    name: "Tofu Veggie Bowl",
    calories: 420,
    protein: 24,
    carbs: 48,
    fat: 14,
    detail: "Tofu • quinoa • roasted veggies",
  },
  {
    id: "seed_pasta_with_meat_sauce",
    name: "Pasta With Meat Sauce",
    calories: 640,
    protein: 35,
    carbs: 72,
    fat: 22,
    detail: "Penne • lean beef • tomato sauce",
  },
  {
    id: "seed_cottage_cheese_bowl",
    name: "Cottage Cheese Bowl",
    calories: 260,
    protein: 28,
    carbs: 18,
    fat: 8,
    detail: "Cottage cheese • berries • chia",
  },
  {
    id: "seed_peanut_butter_toast",
    name: "Peanut Butter Toast",
    calories: 300,
    protein: 11,
    carbs: 31,
    fat: 15,
    detail: "Whole grain toast • peanut butter",
  },
  {
    id: "seed_chicken_quesadilla",
    name: "Chicken Quesadilla",
    calories: 560,
    protein: 36,
    carbs: 42,
    fat: 28,
    detail: "Chicken • tortilla • cheese",
  },
  {
    id: "seed_veggie_omelet",
    name: "Veggie Omelet",
    calories: 290,
    protein: 25,
    carbs: 10,
    fat: 16,
    detail: "Eggs • peppers • mushrooms • onion",
  },
  {
    id: "seed_steak_and_potatoes",
    name: "Steak And Potatoes",
    calories: 690,
    protein: 48,
    carbs: 52,
    fat: 30,
    detail: "Sirloin • roasted potatoes • greens",
  },
  {
    id: "seed_overnight_oats",
    name: "Overnight Oats",
    calories: 360,
    protein: 16,
    carbs: 49,
    fat: 11,
    detail: "Oats • milk • berries",
  },
  {
    id: "seed_poke_bowl",
    name: "Poke Bowl",
    calories: 520,
    protein: 34,
    carbs: 56,
    fat: 16,
    detail: "Ahi tuna • rice • edamame",
  },
  {
    id: "seed_chicken_alfredo",
    name: "Chicken Alfredo",
    calories: 720,
    protein: 42,
    carbs: 58,
    fat: 34,
    detail: "Chicken • fettuccine • alfredo sauce",
  },
  {
    id: "seed_lentil_soup_and_bread",
    name: "Lentil Soup And Bread",
    calories: 410,
    protein: 21,
    carbs: 58,
    fat: 9,
    detail: "Lentil soup • whole grain bread",
  },
  {
    id: "seed_breakfast_burrito",
    name: "Breakfast Burrito",
    calories: 540,
    protein: 29,
    carbs: 46,
    fat: 24,
    detail: "Eggs • beans • tortilla • salsa",
  },
  {
    id: "seed_ground_turkey_bowl",
    name: "Ground Turkey Bowl",
    calories: 500,
    protein: 38,
    carbs: 44,
    fat: 18,
    detail: "Ground turkey • rice • veggies",
  },
  {
    id: "seed_sushi_roll_set",
    name: "Sushi Roll Set",
    calories: 430,
    protein: 21,
    carbs: 62,
    fat: 10,
    detail: "2 rolls • miso soup",
  },
  {
    id: "seed_chickpea_salad",
    name: "Chickpea Salad",
    calories: 370,
    protein: 15,
    carbs: 42,
    fat: 14,
    detail: "Chickpeas • cucumber • tomato",
  },
  {
    id: "seed_chicken_noodle_soup",
    name: "Chicken Noodle Soup",
    calories: 310,
    protein: 23,
    carbs: 28,
    fat: 10,
    detail: "Chicken broth • noodles • veg",
  },
  {
    id: "seed_yogurt_protein_bowl",
    name: "Yogurt Protein Bowl",
    calories: 340,
    protein: 29,
    carbs: 32,
    fat: 10,
    detail: "Skyr • fruit • granola",
  },
  {
    id: "seed_rice_and_beans_plate",
    name: "Rice And Beans Plate",
    calories: 480,
    protein: 17,
    carbs: 74,
    fat: 12,
    detail: "Rice • black beans • pico",
  },
  {
    id: "seed_teriyaki_chicken_plate",
    name: "Teriyaki Chicken Plate",
    calories: 590,
    protein: 37,
    carbs: 68,
    fat: 18,
    detail: "Chicken • rice • teriyaki sauce",
  },
  {
    id: "seed_turkey_chili",
    name: "Turkey Chili",
    calories: 450,
    protein: 34,
    carbs: 38,
    fat: 16,
    detail: "Ground turkey • beans • tomato",
  },
]
